---
title: der chor
timezone: UTC
collections:
  concerts:
    title: Concerts
    output: true
    permalink: "/konzerte/:name"
  people:
    title: Personen
    output: true
    permalink: "/personen/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
    background_color_rgb: rgb(0,0,0)
    theme_image_path: "/images/schatten_und_licht_chor.jpg"
    background_opacity: 0.5
    background_blur: 1px
    font_color: white
    songs:
    - title: ''
      audio_path: ''
- scope:
    path: ''
    type: concerts
  values:
    layout: konzerte
- scope:
    path: ''
    type: people
  values:
    layout: people
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: ''
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
